<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.icy</groupId>
        <artifactId>pom-icy</artifactId>
        <version>3.0.0-a.7</version>
    </parent>

    <groupId>fr.icy.maven</groupId>
    <artifactId>mojo-maven-plugin</artifactId>
    <version>1.0.0-a.7</version>

    <packaging>maven-plugin</packaging>

    <name>Maven plugin for build automation</name>
    <description>Provides tools to generate properties inside extension jar</description>
    <url>https://icy.bioimageanalysis.org/</url>
    <inceptionYear>2025</inceptionYear>

    <scm>
        <url>https://gitlab.pasteur.fr/bia/icy/maven/mojo-maven-plugin</url>
        <tag>v${project.version}</tag>
    </scm>

    <issueManagement>
        <system>GitLab Issues</system>
        <url>https://gitlab.pasteur.fr/bia/icy/maven/mojo-maven-plugin/-/issues</url>
    </issueManagement>
    <ciManagement>
        <system>GitLab CI</system>
        <url>https://gitlab.pasteur.fr/bia/icy/maven/mojo-maven-plugin/-/pipelines</url>
    </ciManagement>

    <organization>
        <name>Institut Pasteur</name>
        <url>https://www.pasteur.fr/</url>
    </organization>

    <licenses>
        <license>
            <name>GNU LGPLv3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>tmusset</id>
            <name>Thomas Musset</name>
            <url>https://icy.bioimageanalysis.org/author/tmusset/</url>
            <roles>
                <role>lead</role>
                <role>developer</role>
                <role>debugger</role>
                <role>reviewer</role>
                <role>support</role>
                <role>maintainer</role>
            </roles>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Thomas Musset</name>
        </contributor>
    </contributors>

    <mailingLists>
        <mailingList>
            <name>Icy</name>
            <post>icy.team@pasteur.fr</post>
        </mailingList>
    </mailingLists>

    <properties>
        <license.licenseName>GNU LGPLv3</license.licenseName>
        <license.copyrightOwners>Institut Pasteur</license.copyrightOwners>

        <maven-core.version>3.9.15</maven-core.version>
        <org.apache.maven.maven-core.version>${maven-core.version}</org.apache.maven.maven-core.version>

        <maven-plugin-api.version>${maven-core.version}</maven-plugin-api.version>
        <org.apache.maven.maven-plugin-api.version>${maven-plugin-api.version}</org.apache.maven.maven-plugin-api.version>

        <maven-plugin-annotations.version>3.15.2</maven-plugin-annotations.version>
        <org.apache.maven.plugin-tools.maven-plugin-annotations.version>${maven-plugin-annotations.version}</org.apache.maven.plugin-tools.maven-plugin-annotations.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-core</artifactId>
            <version>${org.apache.maven.maven-core.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>${org.apache.maven.maven-plugin-api.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <version>${org.apache.maven.plugin-tools.maven-plugin-annotations.version}</version>
        </dependency>

        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>${org.yaml.snakeyaml.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-plugin-plugin</artifactId>
                <version>${maven-plugin-plugin.version}</version>
                <configuration>
                    <!-- Prefix used to invoke this maven plugin: mvn icy-mojo:something -->
                    <goalPrefix>icy-mojo</goalPrefix>
                    <skipErrorNoDescriptorsFound>false</skipErrorNoDescriptorsFound>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-descriptor</id>
                        <goals>
                            <goal>descriptor</goal>
                        </goals>
                    </execution>
                    <!-- Generates help goal (mvn icy-mojo:help) -->
                    <execution>
                        <id>generate-helpmojo</id>
                        <goals>
                            <goal>helpmojo</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>