<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.bia.icy</groupId>
        <artifactId>pom-icy</artifactId>
        <version>3.0.0-a.5</version>
    </parent>

    <groupId>org.bioimageanalysis.icy.maven3</groupId>
    <artifactId>extension-properties-plugin</artifactId>
    <version>1.0.0-a.5</version>

    <packaging>maven-plugin</packaging>

    <name>Maven plugin for build automation</name>
    <description>Provides tools to generate properties inside extension jar</description>
    <url>https://icy.bioimageanalysis.org/</url>
    <inceptionYear>2025</inceptionYear>

    <scm>
        <url>https://gitlab.pasteur.fr/bia/icy/maven/maven-extension-properties</url>
        <tag>v${project.version}</tag>
    </scm>

    <issueManagement>
        <system>GitLab Issues</system>
        <url>https://gitlab.pasteur.fr/bia/icy/maven/maven-extension-properties/-/issues</url>
    </issueManagement>
    <ciManagement>
        <system>GitLab CI</system>
        <url>https://gitlab.pasteur.fr/bia/icy/maven/maven-extension-properties/-/pipelines</url>
    </ciManagement>

    <organization>
        <name>Institut Pasteur</name>
        <url>https://www.pasteur.fr/</url>
    </organization>

    <licenses>
        <license>
            <name>GNU GPLv3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>tmusset</id>
            <name>Thomas Musset</name>
            <url>https://icy.bioimageanalysis.org/author/tmusset/</url>
            <roles>
                <role>lead</role>
                <role>developer</role>
                <role>debugger</role>
                <role>reviewer</role>
                <role>support</role>
                <role>maintainer</role>
            </roles>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Thomas Musset</name>
        </contributor>
    </contributors>

    <mailingLists>
        <mailingList>
            <name>Icy</name>
            <post>icy.team@pasteur.fr</post>
        </mailingList>
    </mailingLists>

    <properties>
        <license.licenseName>GNU LGPLv3</license.licenseName>
        <license.copyrightOwners>Institut Pasteur</license.copyrightOwners>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>3.9.10</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-core</artifactId>
            <version>3.9.10</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <version>3.15.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-plugin-plugin</artifactId>
                <version>3.15.1</version>
                <executions>
                    <execution>
                        <id>default-descriptor</id>
                        <configuration>
                            <goalPrefix>extension-properties</goalPrefix>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>